"""Initial migration for PostgreSQL

Revision ID: 2056aa91ae9f
Revises: 
Create Date: 2026-03-14 19:59:55.115813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2056aa91ae9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_number')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('inventors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_number', sa.String(length=50), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('kind_code', sa.String(length=2), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('abstract_hdfs_path', sa.Text(), nullable=True),
    sa.Column('description_hdfs_path', sa.Text(), nullable=True),
    sa.Column('claims_hdfs_path', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_number')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent_citations',
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint('patent_id', 'citation_id')
    )
    op.create_table('patent_classifications',
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint('patent_id', 'classification_id')
    )
    op.create_table('patent_inventors',
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('inventor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventor_id'], ['inventors.id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint('patent_id', 'inventor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patent_inventors')
    op.drop_table('patent_classifications')
    op.drop_table('patent_citations')
    op.drop_table('concepts')
    op.drop_table('patents')
    op.drop_table('inventors')
    op.drop_table('classifications')
    op.drop_table('citations')
    # ### end Alembic commands ###
